### ISSUE TITLE
"eye" button changing state

### ISSUE THREAD

**Issue by kentonh** [jarrettgreen/SendMeCryptoIssues#1]
The "eye" button is default set to not-crossed-out.
When I tap the eye, it changes to crossed-out state.

Expected: tapping again will change to not-crossed-out.
Actual: Tapping has no noticeable change

**Comment by kentonh** [comment]
On further testing, state will change after the device is locked and unlocked BUT will not change after being cycled once

**Comment by kentonh** [comment]
Might be touch area is too small

**Comment by jarrettgreen** [comment]
![img_1812](https://user-images.githubusercontent.com/1060460/32464886-2e986264-c307-11e7-8e31-7847fc5618fd.jpeg)

**Comment by jarrettgreen** [comment]
Increased the size of the button/icon in `1.0.1`
