### ISSUE TITLE
Value of wallet is NaN

### ISSUE THREAD

**Issue by kentonh** [jarrettgreen/SendMeCryptoIssues#2]
This wallet contains .0103BTC during this screenshot. Shows as NaN.![Image](https://i.imgur.com/6PBydzm.jpg)

**Comment by jarrettgreen** [comment]
Good find. The address looks like it was scanned but I didn't strip out the `bitcoin:` prefix.

**Comment by kentonh** [comment]
I’ve manually edited the address to remove “bitcoin:” but now get 0 value (should be .01, right?

![Image](https://i.imgur.com/b6xWUPH.jpg)

**Comment by jarrettgreen** [comment]
1.0.2 is on it's way to the app store now and parses the address out of the various qr code string versions out there.
