### ISSUE TITLE
Wallet address overlaps with QR icon

### ISSUE THREAD

**Issue by kentonh** [jarrettgreen/SendMeCryptoIssues#3]
![Image](https://i.imgur.com/iVKiY1B.jpg)

**Comment by jarrettgreen** [comment]
Thanks for the find. I'll truncate the public key. This will make it into the next build in TestFlight:

![iphone_6_plus_-_ios_11_0](https://user-images.githubusercontent.com/1060460/32472955-b86beace-c32a-11e7-81c2-c3bfab988f91.png)
